#!/bin/bash

function check_coding_style() {
    local topdir="$(cd $(dirname $0)/../.. && pwd)"
    if [ ! -x "${topdir}/node_modules/.bin/eslint" ]; then
        npm install eslint
    fi
    "${topdir}/node_modules/.bin/eslint" --fix \
        app/ \
        config/ \
        ops/ \
        stylesheets/ \
        static-content/
}

echo Checking coding style
check_coding_style
